# Generated by Django 6.0 on 2026-01-28 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctorprofile_users_docto_latitud_6781b6_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorworkinghour',
            unique_together={('doctor', 'id')},
        ),
        migrations.AddField(
            model_name='doctorworkinghour',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='doctorworkinghour',
            name='day',
        ),
    ]
