# Generated by Django 6.0 on 2026-01-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorprofile_latitude_doctorprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='users_docto_latitud_6781b6_idx'),
        ),
    ]
